site_name: Open Traffic Generator APIs & Data Models
theme:
  name: material
  logo: images/otg-icon-gear-wod.svg
  features:
    - navigation.tabs
markdown_extensions:
  - tables
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

# Page tree
nav:
  - Home: index.md
  - Model: model.md
  - Implementations: implementations.md
  - Clients:
    - Overview: clients.md
    - curl: clients/curl.md
    - otgen: clients/otgen.md
    - snappi: clients/snappi.md
    - gosnappi: clients/gosnappi.md
  - Coding: coding.md
  - Examples: 
    - Overview: examples.md
    - Basic Configurations: examples/basic.md
    - OTG Examples: examples/otg-examples.md
