site_name: Open Traffic Generator APIs & Data Models
repo_url: https://github.com/open-traffic-generator/models
repo_name: open-traffic-generator
edit_uri: ""
theme:
  name: material
  logo: images/otg_icon_white.svg
  favicon: images/favicon.ico
  palette:
    primary: indigo
    accent: indigo
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.instant
    - navigation.tracking
    - navigation.top
markdown_extensions:
  - tables
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
extra:
  analytics:
    provider: google
    property: G-N6X4KDVDJF
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/open-traffic-generator
    - icon: fontawesome/brands/slack
      link: https://ixia-c.slack.com
# Page tree
nav:
  - Home: index.md
  - Model: model.md
  - Implementations: implementations.md
  - Clients:
    - Overview: clients.md
    - curl: clients/curl.md
    - otgen: clients/otgen/README.md
    - snappi: clients/snappi.md
    - gosnappi: clients/gosnappi.md
  - Examples:
    - Overview: examples.md
    - Basic Configurations: examples/basic.md
    - OTG Examples: examples/otg-examples/README.md
