site_name: Open Traffic Generator APIs & Data Models
theme:
  name: material
  features:
    - navigation.tabs

# Page tree
nav:
  - Home: index.md
  - Model: model.md
  - Implementations: implementations.md
  - Clients:
    - Overview: clients.md
    - curl: clients/curl.md
    - otgen: clients/otgen.md
    - snappi: clients/snappi.md
    - gosnappi: clients/gosnappi.md
  - Coding: coding.md
  - Examples: examples.md